steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--platform', 'linux/amd64', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/github-actions-cloud-build-practice/frontend:tag1', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west2-docker.pkg.dev/$PROJECT_ID/github-actions-cloud-build-practice/frontend:tag1']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'frontend', '--image', 'us-west2-docker.pkg.dev/$PROJECT_ID/github-actions-cloud-build-practice/frontend:tag1', '--region', 'us-west2', '--port', '8080']
images:
- 'us-west2-docker.pkg.dev/$PROJECT_ID/github-actions-cloud-build-practice/frontend:tag1'
