name: frontend unit test

on: [push]
#    paths:
#      - "frontend"

defaults:
  run:
    shell: bash
    working-directory: frontend
    
jobs:
  frontend-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm

      - name: Run tests
        run: npm run test
